
spring:

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      # ?????? ?? ? ???? ???? ???? (??) ??
      # (create: ?? ?? ??, create-drop: ?? ? ??, update: ??? ??, validate: ??, none: ???? ??)
      ddl-auto: create
    properties:
      hibernate:
        # ???? SQL ??? ??? ??
        show_sql: true
        # SQL ??? ?? ?? ???
        format_sql: true
    # (??) SQL ??? ??? DEBUG? ???? ???? ??? ? ??
    # logging.level.org.hibernate.SQL=DEBUG 

  # --- Thymeleaf ?? ---
  thymeleaf:
    # (???) ??? ??? ???? ??
    prefix: classpath:/templates/
    # (???) ??? ??? ???
    suffix: .html
    # [??] ?? ??? ??? ?????? HTML ?? ? ?? ?????.
    cache: false